#ifndef ORCA_REGISTERS_H
#define ORCA_REGISTERS_H

/* Beginning of Register Addresses */
#define CTRL_REG_0                0
#define CTRL_REG_1                1
#define CTRL_REG_2                2
#define CTRL_REG_3                3
#define CTRL_REG_4                4
#define KIN_SW_TRIGGER            9
#define FORCE_CMD                 28
#define FORCE_CMD_H               29
#define POS_CMD                   30
#define POS_CMD_H                 31
#define CC_PGAIN                  129
#define CC_IGAIN                  130
#define CC_FGAIN                  131
#define PC_PGAIN                  133
#define PC_IGAIN                  134
#define PC_DVGAIN                 135
#define PC_DEGAIN                 136
#define PC_FSATU                  137
#define PC_FSATU_H                138
#define USER_MAX_TEMP             139
#define USER_MAX_FORCE            140
#define USER_MAX_FORCE_H          141
#define USER_MAX_POWER            142
#define SAFETY_DGAIN              143
#define USER_MAX_COIL_TEMP        147
#define TEMP_ERR_HYSTERESIS       148
#define PC_SOFTSTART_PERIOD       150
#define FORCE_UNITS               151
#define POS_SIGN                  152
#define POS_MAX_VEL               153
#define POS_MAX_ACCEL             154
#define POS_MAX_DECEL             155
#define LOG_PERIOD                162
#define USER_COMMS_TIMEOUT        163
#define USR_MB_BAUD_LO            164
#define USR_MB_BAUD_HI            165
#define FORCE_FILT                166
#define POS_FILT                  167
#define USR_MB_DELAY              168
#define USR_MB_ADDR               169
#define ZERO_MODE                 171
#define AUTO_ZERO_FORCE_N         172
#define AUTO_ZERO_EXIT_MODE       173
#define MB_RS485_MODE             174
#define MB_FORCE_FILTER           175
#define MB_POS_FILTER             176
#define AUTO_ZERO_SPEED_MMPS      177
#define PWM_TIMEOUT_MS            178
#define PWM_TIME_CONST_MS         179
#define PWM_MIN_POS               180
#define PWM_MIN_POS_H             181
#define PWM_MAX_POS               182
#define PWM_MAX_POS_H             183
#define PWM_SERVO_TYPE            184
#define MB_FREQ                   273
#define MODE_OF_OPERATION         317
#define KINEMATIC_STATUS          319
#define KIN_COMPLETE_COUNT        320
#define MOTOR_STATUS              321
#define POS_CURSOR                322
#define POS_CURSOR_H              323
#define BOARD_TEMP                336
#define VDD_FINAL                 338
#define SHAFT_POS_UM              342
#define SHAFT_POSITION_H          343
#define SHAFT_SPEED_MMPS          344
#define SHAFT_SHEED_H             345
#define SHAFT_ACCEL_MMPSS         346
#define SHAFT_ACCEL_H             347
#define FORCE                     348
#define FORCE_H                   349
#define POWER                     350
#define HBA_CURRENT               351
#define HBB_CURRENT               352
#define HBC_CURRENT               353
#define HBD_CURRENT               354
#define AVG_POWER                 355
#define COIL_TEMP                 356
#define SERIAL_NUMBER_LOW         406
#define SERIAL_NUMBER_HIGH        407
#define MAJOR_VERSION             408
#define RELEASE_STATE             409
#define REVISION_NUMBER           410
#define COMMIT_ID_LO              411
#define COMMIT_ID_HI              412
#define STATOR_CONFIG             418
#define WARNING                   431
#define ERROR_0                   432
#define ERROR_1                   433
#define MB_CNT0                   464
#define MB_CNT1                   465
#define MB_CNT2                   466
#define MB_CNT3                   467
#define MB_CNT4                   468
#define MB_CNT5                   469
#define MB_CNT6                   470
#define MB_CNT7                   471
#define MB_CNT8                   472
#define MB_CNT9                   473
#define MB_CNT10                  474
#define MB_CNT11                  475
#define MB_CNT12                  476
#define MB_CNT13                  477
#define MB_CNT14                  478
#define MB_BAUD                   482
#define MB_BAUD_H                 483
#define MB_IF_DELAY               484
#define MB_ADDRESS                485
#define HAPTIC_STATUS             641
#define CONSTANT_FORCE_MN         642
#define CONSTANT_FORCE_MN_H       643
#define S0_GAIN_N_MM              644
#define S0_CENTER_UM              645
#define S0_CENTER_UM_H            646
#define S0_COUPLING               647
#define S0_DEAD_ZONE_MM           648
#define S0_FORCE_SAT_N            649
#define S1_GAIN_N_MM              650
#define S1_CENTER_UM              651
#define S1_CENTER_UM_H            652
#define S1_COUPLING               653
#define S1_DEAD_ZONE_MM           654
#define S1_FORCE_SAT_N            655
#define S2_GAIN_N_MM              656
#define S2_CENTER_UM              657
#define S2_CENTER_UM_H            658
#define S2_COUPLING               659
#define S2_DEAD_ZONE_MM           660
#define S2_FORCE_SAT_N            661
#define D0_GAIN_NS_MM             662
#define I0_GAIN_NS2_MM            663
#define O0_GAIN_N                 664
#define O0_TYPE                   665
#define O0_FREQ_DHZ               666
#define O0_DUTY                   667
#define O1_GAIN_N                 668
#define O1_TYPE                   669
#define O1_FREQ_DHZ               670
#define O1_DUTY                   671
#define CONST_FORCE_FILTER        672
#define HAPTIC_SOFTSTART          673
#define ILOOP_DIN                 756
#define ILOOP_OUT_CH1             757
#define ILOOP_OUT_CH2             758
#define ILOOP_IN                  759
#define ILOOP_CONFIG              761
#define ILOOP_FORCE_MIN           762
#define ILOOP_FORCE_MIN_HI        763
#define ILOOP_FORCE_MAX           764
#define ILOOP_FORCE_MAX_HI        765
#define ILOOP_POS_MIN             766
#define ILOOP_POS_MIN_HI          767
#define ILOOP_POS_MAX             768
#define ILOOP_POS_MAX_HI          769
#define ILOOP_KIN_TYPE            770
#define ILOOP_D0_HIGH_ID          771
#define ILOOP_D0_LOW_ID           772
#define ILOOP_D1_HIGH_ID          773
#define ILOOP_D1_LOW_ID           774
#define ILOOP_D2_HIGH_ID          775
#define ILOOP_D2_LOW_ID           776
#define KIN0_POSITION_TARGET      780
#define KIN0_POSITION_TARGET_H    781
#define KIN0_MOTION_TIME          782
#define KIN0_MOTION_TIME_H        783
#define KIN0_DELAY_TIME           784
#define KIN0_MOTION_CONFIG        785
#define KIN1_POSITION_TARGET      786
#define KIN1_POSITION_TARGET_H    787
#define KIN1_MOTION_TIME          788
#define KIN1_MOTION_TIME_H        789
#define KIN1_DELAY_TIME           790
#define KIN1_MOTION_CONFIG        791
#define KIN2_POSITION_TARGET      792
#define KIN2_POSITION_TARGET_H    793
#define KIN2_MOTION_TIME          794
#define KIN2_MOTION_TIME_H        795
#define KIN2_DELAY_TIME           796
#define KIN2_MOTION_CONFIG        797
#define KIN3_POSITION_TARGET      798
#define KIN3_POSITION_TARGET_H    799
#define KIN3_MOTION_TIME          800
#define KIN3_MOTION_TIME_H        801
#define KIN3_DELAY_TIME           802
#define KIN3_MOTION_CONFIG        803
#define KIN4_POSITION_TARGET      804
#define KIN4_POSITION_TARGET_H    805
#define KIN4_MOTION_TIME          806
#define KIN4_MOTION_TIME_H        807
#define KIN4_DELAY_TIME           808
#define KIN4_MOTION_CONFIG        809
#define KIN5_POSITION_TARGET      810
#define KIN5_POSITION_TARGET_H    811
#define KIN5_MOTION_TIME          812
#define KIN5_MOTION_TIME_H        813
#define KIN5_DELAY_TIME           814
#define KIN5_MOTION_CONFIG        815
#define KIN6_POSITION_TARGET      816
#define KIN6_POSITION_TARGET_H    817
#define KIN6_MOTION_TIME          818
#define KIN6_MOTION_TIME_H        819
#define KIN6_DELAY_TIME           820
#define KIN6_MOTION_CONFIG        821
#define KIN7_POSITION_TARGET      822
#define KIN7_POSITION_TARGET_H    823
#define KIN7_MOTION_TIME          824
#define KIN7_MOTION_TIME_H        825
#define KIN7_DELAY_TIME           826
#define KIN7_MOTION_CONFIG        827
#define KIN8_POSITION_TARGET      828
#define KIN8_POSITION_TARGET_H    829
#define KIN8_MOTION_TIME          830
#define KIN8_MOTION_TIME_H        831
#define KIN8_DELAY_TIME           832
#define KIN8_MOTION_CONFIG        833
#define KIN9_POSITION_TARGET      834
#define KIN9_POSITION_TARGET_H    835
#define KIN9_MOTION_TIME          836
#define KIN9_MOTION_TIME_H        837
#define KIN9_DELAY_TIME           838
#define KIN9_MOTION_CONFIG        839
#define KIN10_POSITION_TARGET     840
#define KIN10_POSITION_TARGET_H   841
#define KIN10_MOTION_TIME         842
#define KIN10_MOTION_TIME_H       843
#define KIN10_DELAY_TIME          844
#define KIN10_MOTION_CONFIG       845
#define KIN11_POSITION_TARGET     846
#define KIN11_POSITION_TARGET_H   847
#define KIN11_MOTION_TIME         848
#define KIN11_MOTION_TIME_H       849
#define KIN11_DELAY_TIME          850
#define KIN11_MOTION_CONFIG       851
#define KIN12_POSITION_TARGET     852
#define KIN12_POSITION_TARGET_H   853
#define KIN12_MOTION_TIME         854
#define KIN12_MOTION_TIME_H       855
#define KIN12_DELAY_TIME          856
#define KIN12_MOTION_CONFIG       857
#define KIN13_POSITION_TARGET     858
#define KIN13_POSITION_TARGET_H   859
#define KIN13_MOTION_TIME         860
#define KIN13_MOTION_TIME_H       861
#define KIN13_DELAY_TIME          862
#define KIN13_MOTION_CONFIG       863
#define KIN14_POSITION_TARGET     864
#define KIN14_POSITION_TARGET_H   865
#define KIN14_MOTION_TIME         866
#define KIN14_MOTION_TIME_H       867
#define KIN14_DELAY_TIME          868
#define KIN14_MOTION_CONFIG       869
#define KIN15_POSITION_TARGET     870
#define KIN15_POSITION_TARGET_H   871
#define KIN15_MOTION_TIME         872
#define KIN15_MOTION_TIME_H       873
#define KIN15_DELAY_TIME          874
#define KIN15_MOTION_CONFIG       875
#define KIN16_POSITION_TARGET     876
#define KIN16_POSITION_TARGET_H   877
#define KIN16_MOTION_TIME         878
#define KIN16_MOTION_TIME_H       879
#define KIN16_DELAY_TIME          880
#define KIN16_MOTION_CONFIG       881
#define KIN17_POSITION_TARGET     882
#define KIN17_POSITION_TARGET_H   883
#define KIN17_MOTION_TIME         884
#define KIN17_MOTION_TIME_H       885
#define KIN17_DELAY_TIME          886
#define KIN17_MOTION_CONFIG       887
#define KIN18_POSITION_TARGET     888
#define KIN18_POSITION_TARGET_H   889
#define KIN18_MOTION_TIME         890
#define KIN18_MOTION_TIME_H       891
#define KIN18_DELAY_TIME          892
#define KIN18_MOTION_CONFIG       893
#define KIN19_POSITION_TARGET     894
#define KIN19_POSITION_TARGET_H   895
#define KIN19_MOTION_TIME         896
#define KIN19_MOTION_TIME_H       897
#define KIN19_DELAY_TIME          898
#define KIN19_MOTION_CONFIG       899
#define KIN20_POSITION_TARGET     900
#define KIN20_POSITION_TARGET_H   901
#define KIN20_MOTION_TIME         902
#define KIN20_MOTION_TIME_H       903
#define KIN20_DELAY_TIME          904
#define KIN20_MOTION_CONFIG       905
#define KIN21_POSITION_TARGET     906
#define KIN21_POSITION_TARGET_H   907
#define KIN21_MOTION_TIME         908
#define KIN21_MOTION_TIME_H       909
#define KIN21_DELAY_TIME          910
#define KIN21_MOTION_CONFIG       911
#define KIN22_POSITION_TARGET     912
#define KIN22_POSITION_TARGET_H   913
#define KIN22_MOTION_TIME         914
#define KIN22_MOTION_TIME_H       915
#define KIN22_DELAY_TIME          916
#define KIN22_MOTION_CONFIG       917
#define KIN23_POSITION_TARGET     918
#define KIN23_POSITION_TARGET_H   919
#define KIN23_MOTION_TIME         920
#define KIN23_MOTION_TIME_H       921
#define KIN23_DELAY_TIME          922
#define KIN23_MOTION_CONFIG       923
#define KIN24_POSITION_TARGET     924
#define KIN24_POSITION_TARGET_H   925
#define KIN24_MOTION_TIME         926
#define KIN24_MOTION_TIME_H       927
#define KIN24_DELAY_TIME          928
#define KIN24_MOTION_CONFIG       929
#define KIN25_POSITION_TARGET     930
#define KIN25_POSITION_TARGET_H   931
#define KIN25_MOTION_TIME         932
#define KIN25_MOTION_TIME_H       933
#define KIN25_DELAY_TIME          934
#define KIN25_MOTION_CONFIG       935
#define KIN26_POSITION_TARGET     936
#define KIN26_POSITION_TARGET_H   937
#define KIN26_MOTION_TIME         938
#define KIN26_MOTION_TIME_H       939
#define KIN26_DELAY_TIME          940
#define KIN26_MOTION_CONFIG       941
#define KIN27_POSITION_TARGET     942
#define KIN27_POSITION_TARGET_H   943
#define KIN27_MOTION_TIME         944
#define KIN27_MOTION_TIME_H       945
#define KIN27_DELAY_TIME          946
#define KIN27_MOTION_CONFIG       947
#define KIN28_POSITION_TARGET     948
#define KIN28_POSITION_TARGET_H   949
#define KIN28_MOTION_TIME         950
#define KIN28_MOTION_TIME_H       951
#define KIN28_DELAY_TIME          952
#define KIN28_MOTION_CONFIG       953
#define KIN29_POSITION_TARGET     954
#define KIN29_POSITION_TARGET_H   955
#define KIN29_MOTION_TIME         956
#define KIN29_MOTION_TIME_H       957
#define KIN29_DELAY_TIME          958
#define KIN29_MOTION_CONFIG       959
#define KIN30_POSITION_TARGET     960
#define KIN30_POSITION_TARGET_H   961
#define KIN30_MOTION_TIME         962
#define KIN30_MOTION_TIME_H       963
#define KIN30_DELAY_TIME          964
#define KIN30_MOTION_CONFIG       965
#define KIN31_POSITION_TARGET     966
#define KIN31_POSITION_TARGET_H   967
#define KIN31_MOTION_TIME         968
#define KIN31_MOTION_TIME_H       969
#define KIN31_DELAY_TIME          970
#define KIN31_MOTION_CONFIG       971
#define KIN_HOME_ID               972

/* Beginning of Register Value Definitions */

// CTRL_REG_0 Definitions
#define CTRL_REG_0_RESET_ORCA_Mask  0x1
#define CTRL_REG_0_RESET_ORCA_Shift 0
#define CTRL_REG_0_CLEAR_ERR_Mask   0x2
#define CTRL_REG_0_CLEAR_ERR_Shift  1
#define CTRL_REG_0_ZERO_POS_Mask    0x4
#define CTRL_REG_0_ZERO_POS_Shift   2
#define CTRL_REG_0_INVERT_POS_Mask  0x8
#define CTRL_REG_0_INVERT_POS_Shift 3

// CTRL_REG_1 Definitions
#define CTRL_REG_1_HALL_GAIN_SET_Mask      0x8
#define CTRL_REG_1_HALL_GAIN_SET_Shift     3
#define CTRL_REG_1_CURRENT_GAIN_SET_Mask   0x10
#define CTRL_REG_1_CURRENT_GAIN_SET_Shift  4
#define CTRL_REG_1_HALL_ZERO_FLAG_Mask     0x20
#define CTRL_REG_1_HALL_ZERO_FLAG_Shift    5
#define CTRL_REG_1_CURRENT_ZERO_FLAG_Mask  0x40
#define CTRL_REG_1_CURRENT_ZERO_FLAG_Shift 6
#define CTRL_REG_1_PC_GAIN_APPLY_Mask      0x400
#define CTRL_REG_1_PC_GAIN_APPLY_Shift     10
#define CTRL_REG_1_CC_GAIN_APPLY_Mask      0x800
#define CTRL_REG_1_CC_GAIN_APPLY_Shift     11

// CTRL_REG_2 Definitions
#define CTRL_REG_2_STATOR_CAL_SAVE_Mask   0x4
#define CTRL_REG_2_STATOR_CAL_SAVE_Shift  2
#define CTRL_REG_2_SHAFT_CAL_SAVE_Mask    0x8
#define CTRL_REG_2_SHAFT_CAL_SAVE_Shift   3
#define CTRL_REG_2_FORCE_CAL_SAVE_Mask    0x10
#define CTRL_REG_2_FORCE_CAL_SAVE_Shift   4
#define CTRL_REG_2_TUNING_SAVE_Mask       0x20
#define CTRL_REG_2_TUNING_SAVE_Shift      5
#define CTRL_REG_2_USER_OPTION_SAVE_Mask  0x40
#define CTRL_REG_2_USER_OPTION_SAVE_Shift 6
#define CTRL_REG_2_KINEMATIC_SAVE_Mask    0x80
#define CTRL_REG_2_KINEMATIC_SAVE_Shift   7
#define CTRL_REG_2_IOSH_SAVE_Mask         0x100
#define CTRL_REG_2_IOSH_SAVE_Shift        8
#define CTRL_REG_2_HAPTIC_SAVE_Mask       0x200
#define CTRL_REG_2_HAPTIC_SAVE_Shift      9
#define CTRL_REG_2_TRIM_SAVE_Mask         0x400
#define CTRL_REG_2_TRIM_SAVE_Shift        10

// CTRL_REG_3 Definitions
#define CTRL_REG_3_SLEEP_MODE          1
#define CTRL_REG_3_FORCE_MODE          2
#define CTRL_REG_3_POSITION_MODE       3
#define CTRL_REG_3_HAPTIC_MODE         4
#define CTRL_REG_3_KINEMATIC_MODE      5
#define CTRL_REG_3_VOLTAGE_MODE        6
#define CTRL_REG_3_CURRENT_MODE        7
#define CTRL_REG_3_IOSH_FORCE_MODE     8
#define CTRL_REG_3_IOSH_POSITION_MODE  9
#define CTRL_REG_3_IOSH_KINEMATIC_MODE 10
#define CTRL_REG_3_PULSE_WIDTH_MODE    11
#define CTRL_REG_3_STATOR_CAL_MODE     50
#define CTRL_REG_3_FORCE_CAL_MODE      51
#define CTRL_REG_3_SHAFT_CAL_MODE      52
#define CTRL_REG_3_ADC_CAL_MODE        53
#define CTRL_REG_3_STEP_TEST_MODE      54
#define CTRL_REG_3_AUTO_ZERO_MODE      55

// CTRL_REG_4 Definitions
#define CTRL_REG_4_TUNING_DEFAULTS_Mask         0x2
#define CTRL_REG_4_TUNING_DEFAULTS_Shift        1
#define CTRL_REG_4_MOTOR_OPTIONS_DEFAULTS_Mask  0x4
#define CTRL_REG_4_MOTOR_OPTIONS_DEFAULTS_Shift 2
#define CTRL_REG_4_MODBUS_DEFAULTS_Mask         0x8
#define CTRL_REG_4_MODBUS_DEFAULTS_Shift        3
#define CTRL_REG_4_KINEMATIC_DEFAULTS_Mask      0x10
#define CTRL_REG_4_KINEMATIC_DEFAULTS_Shift     4
#define CTRL_REG_4_HAPTIC_DEFAULTS_Mask         0x20
#define CTRL_REG_4_HAPTIC_DEFAULTS_Shift        5
#define CTRL_REG_4_IOSH_DEFAULTS_Mask           0x40
#define CTRL_REG_4_IOSH_DEFAULTS_Shift          6
#define CTRL_REG_4_PULSE_WIDTH_DEFAULTS_Mask    0x80
#define CTRL_REG_4_PULSE_WIDTH_DEFAULTS_Shift   7

// FORCE_UNITS Definitions
#define FORCE_UNITS_FORCEUNITS_Mask  0x1
#define FORCE_UNITS_FORCEUNITS_Shift 0

// POS_SIGN Definitions
#define POS_SIGN_POSSIGN_Mask  0x1
#define POS_SIGN_POSSIGN_Shift 0

// ZERO_MODE Definitions
#define ZERO_MODE_NEGATIVE_ZEROING  0
#define ZERO_MODE_MANUAL_ZEROING    1
#define ZERO_MODE_AUTO_ZERO_ENABLED 2
#define ZERO_MODE_AUTO_ZERO_ON_BOOT 3
#define ZERO_MODE_IOSH_AUTO_ZEROING 4

// AUTO_ZERO_EXIT_MODE Definitions
#define AUTO_ZERO_EXIT_MODE_SLEEP_MODE       1
#define AUTO_ZERO_EXIT_MODE_FORCE_MODE       2
#define AUTO_ZERO_EXIT_MODE_POSITION_MODE    3
#define AUTO_ZERO_EXIT_MODE_HAPTIC_MODE      4
#define AUTO_ZERO_EXIT_MODE_KINEMATIC_MODE   5
#define AUTO_ZERO_EXIT_MODE_PULSE_WIDTH_MODE 11

// MB_RS485_MODE Definitions
#define MB_RS485_MODE_RS485MODE_Mask  0x1
#define MB_RS485_MODE_RS485MODE_Shift 0

// PWM_SERVO_TYPE Definitions
#define PWM_SERVO_TYPE_PWM_180_DEG 0
#define PWM_SERVO_TYPE_PWM_270_DEG 1

// MODE_OF_OPERATION Definitions
#define MODE_OF_OPERATION_SLEEP_MODE          1
#define MODE_OF_OPERATION_FORCE_MODE          2
#define MODE_OF_OPERATION_POSITION_MODE       3
#define MODE_OF_OPERATION_HAPTIC_MODE         4
#define MODE_OF_OPERATION_KINEMATIC_MODE      5
#define MODE_OF_OPERATION_VOLTAGE_MODE        6
#define MODE_OF_OPERATION_CURRENT_MODE        7
#define MODE_OF_OPERATION_IOSH_FORCE_MODE     8
#define MODE_OF_OPERATION_IOSH_POSITION_MODE  9
#define MODE_OF_OPERATION_IOSH_KINEMATIC_MODE 10
#define MODE_OF_OPERATION_PULSE_WIDTH_MODE    11
#define MODE_OF_OPERATION_STATOR_CAL_MODE     50
#define MODE_OF_OPERATION_FORCE_CAL_MODE      51
#define MODE_OF_OPERATION_SHAFT_CAL_MODE      52
#define MODE_OF_OPERATION_ADC_CAL_MODE        53
#define MODE_OF_OPERATION_STEP_TEST_MODE      54
#define MODE_OF_OPERATION_AUTO_ZERO_MODE      55

// KINEMATIC_STATUS Definitions
#define KINEMATIC_STATUS_MOTIONID_Mask  0x7FFF
#define KINEMATIC_STATUS_MOTIONID_Shift 0
#define KINEMATIC_STATUS_RUNNING_Mask   0x8000
#define KINEMATIC_STATUS_RUNNING_Shift  15

// MOTOR_STATUS Definitions
#define MOTOR_STATUS_AUTO_ZERO_COMPLETE_Mask  0x1
#define MOTOR_STATUS_AUTO_ZERO_COMPLETE_Shift 0
#define MOTOR_STATUS_AUTO_ZERO_RUNNING_Mask   0x2
#define MOTOR_STATUS_AUTO_ZERO_RUNNING_Shift  1
#define MOTOR_STATUS_POS_MODE_MOVING_Mask     0x4
#define MOTOR_STATUS_POS_MODE_MOVING_Shift    2

// STATOR_CONFIG Definitions
#define STATOR_CONFIG_ORCA_6_24  0
#define STATOR_CONFIG_ORCA_6_48  1
#define STATOR_CONFIG_ORCA_15_48 2
#define STATOR_CONFIG_ORCA_3_12  3
#define STATOR_CONFIG_ORCA_3_36  4

// WARNING Definitions
#define WARNING_IOSH_AUTO_ZERO_Mask  0x1
#define WARNING_IOSH_AUTO_ZERO_Shift 0

// ERROR_0 Definitions
#define ERROR_0_CONFIG_INVALID_Mask          0x1
#define ERROR_0_CONFIG_INVALID_Shift         0
#define ERROR_0_FORCE_CONTROL_CLIPPING_Mask  0x20
#define ERROR_0_FORCE_CONTROL_CLIPPING_Shift 5
#define ERROR_0_MAX_TEMP_EXCEEDED_Mask       0x40
#define ERROR_0_MAX_TEMP_EXCEEDED_Shift      6
#define ERROR_0_MAX_FORCE_EXCEEDED_Mask      0x80
#define ERROR_0_MAX_FORCE_EXCEEDED_Shift     7
#define ERROR_0_MAX_POWER_EXCEEDED_Mask      0x100
#define ERROR_0_MAX_POWER_EXCEEDED_Shift     8
#define ERROR_0_SHAFT_IMAGE_FAILED_Mask      0x200
#define ERROR_0_SHAFT_IMAGE_FAILED_Shift     9
#define ERROR_0_VOLTAGE_INVALID_Mask         0x400
#define ERROR_0_VOLTAGE_INVALID_Shift        10
#define ERROR_0_COMMS_TIMEOUT_Mask           0x800
#define ERROR_0_COMMS_TIMEOUT_Shift          11
#define ERROR_0_AUTO_ZERO_FAILED_Mask        0x2000
#define ERROR_0_AUTO_ZERO_FAILED_Shift       13

// ERROR_1 Definitions
#define ERROR_1_CONFIG_INVALID_Mask          0x1
#define ERROR_1_CONFIG_INVALID_Shift         0
#define ERROR_1_FORCE_CONTROL_CLIPPING_Mask  0x20
#define ERROR_1_FORCE_CONTROL_CLIPPING_Shift 5
#define ERROR_1_MAX_TEMP_EXCEEDED_Mask       0x40
#define ERROR_1_MAX_TEMP_EXCEEDED_Shift      6
#define ERROR_1_MAX_FORCE_EXCEEDED_Mask      0x80
#define ERROR_1_MAX_FORCE_EXCEEDED_Shift     7
#define ERROR_1_MAX_POWER_EXCEEDED_Mask      0x100
#define ERROR_1_MAX_POWER_EXCEEDED_Shift     8
#define ERROR_1_SHAFT_IMAGE_FAILED_Mask      0x200
#define ERROR_1_SHAFT_IMAGE_FAILED_Shift     9
#define ERROR_1_VOLTAGE_INVALID_Mask         0x400
#define ERROR_1_VOLTAGE_INVALID_Shift        10
#define ERROR_1_COMMS_TIMEOUT_Mask           0x800
#define ERROR_1_COMMS_TIMEOUT_Shift          11
#define ERROR_1_AUTO_ZERO_FAILED_Mask        0x2000
#define ERROR_1_AUTO_ZERO_FAILED_Shift       13

// HAPTIC_STATUS Definitions
#define HAPTIC_STATUS_CONSTANT_Mask      0x1
#define HAPTIC_STATUS_CONSTANT_Shift     0
#define HAPTIC_STATUS_SPRING_0_Mask      0x2
#define HAPTIC_STATUS_SPRING_0_Shift     1
#define HAPTIC_STATUS_SPRING_1_Mask      0x4
#define HAPTIC_STATUS_SPRING_1_Shift     2
#define HAPTIC_STATUS_SPRING_2_Mask      0x8
#define HAPTIC_STATUS_SPRING_2_Shift     3
#define HAPTIC_STATUS_DAMPER_Mask        0x10
#define HAPTIC_STATUS_DAMPER_Shift       4
#define HAPTIC_STATUS_INERTIA_Mask       0x20
#define HAPTIC_STATUS_INERTIA_Shift      5
#define HAPTIC_STATUS_OSCILLATOR_0_Mask  0x40
#define HAPTIC_STATUS_OSCILLATOR_0_Shift 6
#define HAPTIC_STATUS_OSCILLATOR_1_Mask  0x80
#define HAPTIC_STATUS_OSCILLATOR_1_Shift 7

// Sn_COUPLING Definitions
#define Sn_COUPLING_BOTH     0
#define Sn_COUPLING_POSITIVE 1
#define Sn_COUPLING_NEGATIVE 2

// On_TYPE Definitions
#define On_TYPE_SQUARE   0
#define On_TYPE_SINE     1
#define On_TYPE_TRIANGLE 2
#define On_TYPE_SAWTOOTH 3

// ILOOP_DIN Definitions
#define ILOOP_DIN_DIN0_Mask  0x1
#define ILOOP_DIN_DIN0_Shift 0
#define ILOOP_DIN_DIN1_Mask  0x2
#define ILOOP_DIN_DIN1_Shift 1
#define ILOOP_DIN_DIN2_Mask  0x4
#define ILOOP_DIN_DIN2_Shift 2
#define ILOOP_DIN_DIN3_Mask  0x8
#define ILOOP_DIN_DIN3_Shift 3

// ILOOP_CONFIG Definitions
#define ILOOP_CONFIG_CH1_Mask      0x3
#define ILOOP_CONFIG_CH1_Shift     0
#define ILOOP_CONFIG_CH2_Mask      0xC
#define ILOOP_CONFIG_CH2_Shift     2
#define ILOOP_CONFIG_IN_MODE_Mask  0x30
#define ILOOP_CONFIG_IN_MODE_Shift 4
#define ILOOP_CONFIG_RANGE_Mask    0x40
#define ILOOP_CONFIG_RANGE_Shift   6

// ILOOP_KIN_TYPE Definitions
#define ILOOP_KIN_TYPE_RISING_EDGE 0
#define ILOOP_KIN_TYPE_BOTH_EDGES  1

// KINn_MOTION_CONFIG Definitions
#define KINn_MOTION_CONFIG_CHAIN_Mask    0x1
#define KINn_MOTION_CONFIG_CHAIN_Shift   0
#define KINn_MOTION_CONFIG_TYPE_Mask     0x6
#define KINn_MOTION_CONFIG_TYPE_Shift    1
#define KINn_MOTION_CONFIG_CHAINID_Mask  0xF8
#define KINn_MOTION_CONFIG_CHAINID_Shift 3

#define ORCA_REG_SIZE 973

#endif // ORCA_REGISTERS_H
